---
- name: install dependencies
  command: yum install -y httpd wget php-fpm php-mysqli php-json php php-devel
  become: true

- name: Make sure apache is running
  systemd:
    state: started
    name: httpd
