---
- name: install dependencies
  command: yum install -y httpd wget php-fpm php-mysqli php-json php php-devel
  become: true

- name: Make sure apache is running
  systemd:
    state: started
    name: httpd
    
- name: Installing php extensions
     yum:
       name:
          - php-mbstring
          - php-xml
       state: present

- name: Restart apache httpd
  service:
        name: httpd
        state: restarted

- name: Restart php-fpm
  service:
      name: php-fpm
      state: restarted
